### ISSUE TITLE
Docs: Improved Structure for "adding packages" to help contributors find information

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan-center-index#13673]
This has been a long standing short coming that make it difficult for new contributors to learn some of the finer details and costs time on the reviewers to help pull requests get merged - and less important but notably the build resources are not insignificant when dozens of commits are pushed trying to correct issues.

🔎  Preview of the direction: https://github.com/conan-io/conan-center-index/compare/master...prince-chrismc:conan-center-index:docs/seperate-by-method?expand=1

### Proposed Structures

- [x] Developing recipes locally #13102 
        - This will be the single location for all the commands you need to contribute to CCI
        - One reference package for everything (`fmt` was picked since it has all the supported configurations of c3i)
- [x] Dedicated "adding packages" folder #13736
- [ ] Break down content by methods (see below)
- [x] New content for missing section and 2.0 changes

#### Break down content by

break down methods into their own files (there will be some grouping based on size like "configure, config_options, and validate" would be an example)
  
- [ ] one file for general "files and folders" which lists a very high level of files and what they contain. #15004
- [x] packaging policy #14211
- [x] patching policy #14377
- [x] reviewing #14491
- [x] dependencies #14833 
- [ ] readme #15004

### Possible Future Work

- Some good suggestions in https://github.com/conan-io/conan-center-index/pull/14211 for "build and package"
- There are a lot of docs that could be moved to the main docs.conan.io side of things that are not specific to ConanCenterIndex

### Notable changes

- FAQs and Error Knowledge will point to the new folder and serve to direct people to the "how" answer... the why might stay (TBD how it unfolds)
- everything about "code in the `recipes/` should be in this new section

### Similar efforts

The main Conan docs have gotten the same treatment

![image](https://user-images.githubusercontent.com/16867443/197270852-3d8318d9-9df4-4d4b-9eb4-764adf438879.png)
